@api = http://localhost:4000/api/v1/games


### Todas los juegos
GET {{api}}



### Cantidad de juegos
GET {{api}}/count



### Busqueda de juego por ID
GET {{api}}/8089d6b8-0da1-4869-b5e9-1d6c38bb8cb1



### Creación de un juego
POST {{api}}
Content-Type: application/json

{
    "title": "Duke Nukem 3D",
    "description": "blood shooter game"
}



### Edición de un juego
PUT {{api}}/a4fc812f-d8e8-4a00-84a6-b26b30369273
Content-Type: application/json

{
    "title": "Primera tarea creada. (editada)",
    "description": "Hoy hay clase. *editado)"
}

###
DELETE {{api}}/a4fc812f-d8e8-4a00-84a6-b26b30369273
